### ISSUE TITLE
Build error with GCC 6.2 (on Cray Piz-Daint)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/libsonata#51]
I haven't looked into details (didn't try locally) but while building py-libsonata with GCC 6.2.0:

```bash
==> Installing py-libsonata
==> Searching for binary cache of py-libsonata
==> Warning: No Spack mirrors are currently configured
==> No binary for py-libsonata found: installing from source
==> Cloning git repository: https://github.com/BlueBrain/libsonata.git at tag v0.1.0
Note: checking out 'dae732e7dca3f10984600e132da4df21aea028ee'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> No checksum needed when fetching with git
==> Already staged py-libsonata-0.1.0-hc2rlkqv7lkx4b3ea36ukzs2rblnhep5 in /apps/hbp/ich002/hbp-spack-deployments/softwares/09-10-2019/sources/spack/var/spack/stage/py-libsonata-0.1.0-hc2rlkqv7lkx4b3ea36ukzs2rblnhep5
==> No patches needed for py-libsonata
==> Building py-libsonata [PythonPackage]
==> Executing phase: 'build'
==> '/opt/python/2.7.15.1/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
/apps/hbp/ich002/hbp-spack-deployments/softwares/09-10-2019/install/install/cray-cnl6-haswell/gcc-6.2.0/py-setuptools-scm-3.1.0-pttzb3/lib/python2.7/site-packages/setuptools_scm/git.py:68: UserWarning: "/tmp/bp000174/spack-stage/spack-stage-LeVlKk/libsonata" is shallow and may cause errors
  warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))
running build
running build_ext
-- Found PythonInterp: /opt/python/2.7.15.1/bin/python2.7 (found version "2.7.15")
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Cray Programming Environment 2.5.15 C
-- Check for working C compiler: /apps/hbp/ich002/hbp-spack-deployments/softwares/09-10-2019/sources/spack/lib/spack/env/gcc/gcc
-- Check for working C compiler: /apps/hbp/ich002/hbp-spack-deployments/softwares/09-10-2019/sources/spack/lib/spack/env/gcc/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.5.15 CXX
-- Check for working CXX compiler: /apps/hbp/ich002/hbp-spack-deployments/softwares/09-10-2019/sources/spack/lib/spack/env/gcc/g++
-- Check for working CXX compiler: /apps/hbp/ich002/hbp-spack-deployments/softwares/09-10-2019/sources/spack/lib/spack/env/gcc/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found HDF5: /opt/cray/pe/hdf5/1.8.16/GNU/5.1/lib/libhdf5.so (found version "1.8.16")
-- Version: 5.2.1
-- Build type:
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Success
-- Performing Test SUPPORTS_INITIALIZER_LIST
-- Performing Test SUPPORTS_INITIALIZER_LIST - Success
-- Performing Test SUPPORTS_ENUM_BASE
-- Performing Test SUPPORTS_ENUM_BASE - Success
-- Performing Test SUPPORTS_TYPE_TRAITS
-- Performing Test SUPPORTS_TYPE_TRAITS - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Looking for open
-- Looking for open - found
-- Found PythonLibs: /opt/python/2.7.15.1/lib/libpython2.7.so
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/bp000174/spack-stage/spack-stage-LeVlKk/libsonata/build/temp.linux-x86_64-2.7
Scanning dependencies of target sonata_static
[ 10%] Building CXX object CMakeFiles/sonata_static.dir/src/edge_index.cpp.o
[ 20%] Building CXX object CMakeFiles/sonata_static.dir/src/common.cpp.o
[ 30%] Building CXX object CMakeFiles/sonata_static.dir/src/edges.cpp.o
[ 40%] Building CXX object CMakeFiles/sonata_static.dir/src/version.cpp.o
[ 50%] Building CXX object CMakeFiles/sonata_static.dir/src/hdf5_mutex.cpp.o
[ 60%] Building CXX object CMakeFiles/sonata_static.dir/src/population.cpp.o
[ 70%] Building CXX object CMakeFiles/sonata_static.dir/src/nodes.cpp.o
[ 80%] Linking CXX static library libsonata.a
[ 80%] Built target sonata_static
Scanning dependencies of target sonata_python
[ 90%] Building CXX object python/CMakeFiles/sonata_python.dir/bindings.cpp.o
[100%] Linking CXX shared module ../../lib.linux-x86_64-2.7/libsonata.so
lto1: internal compiler error: invalid line in the resolution file
0x6268d2 lto_resolution_read
	../../cray-gcc-6.2.0/gcc/lto/lto.c:1910
0x6268d2 lto_file_read
	../../cray-gcc-6.2.0/gcc/lto/lto.c:2090
0x6268d2 read_cgraph_and_symbols
	../../cray-gcc-6.2.0/gcc/lto/lto.c:2804
0x6268d2 lto_main()
	../../cray-gcc-6.2.0/gcc/lto/lto.c:3304
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /opt/gcc/6.2.0/bin/../snos/bin/g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
/usr/bin/X11/sha1sum: ../../lib.linux-x86_64-2.7/libsonata.so: No such file or directory
collect2: error: ld returned 1 exit status
python/CMakeFiles/sonata_python.dir/build.make:85: recipe for target '../lib.linux-x86_64-2.7/libsonata.so' failed
gmake[3]: *** [../lib.linux-x86_64-2.7/libsonata.so] Error 1
CMakeFiles/Makefile2:289: recipe for target 'python/CMakeFiles/sonata_python.dir/all' failed
gmake[2]: *** [python/CMakeFiles/sonata_python.dir/all] Error 2
CMakeFiles/Makefile2:301: recipe for target 'python/CMakeFiles/sonata_python.dir/rule' failed
gmake[1]: *** [python/CMakeFiles/sonata_python.dir/rule] Error 2
Makefile:227: recipe for target 'sonata_python' failed
gmake: *** [sonata_python] Error 2
Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    use_scm_version=True,
  File "/apps/hbp/ich002/hbp-spack-deployments/softwares/09-10-2019/install/install/cray-cnl6-haswell/gcc-6.2.0/py-setuptools-40.4.3-pqb57s/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/2.7.15.1/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/python/2.7.15.1/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.7.15.1/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/python/2.7.15.1/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/opt/python/2.7.15.1/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/python/2.7.15.1/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 68, in run
    self.build_extension(ext)
  File "setup.py", line 106, in build_extension
    ["cmake", "--build", "."] + build_args, cwd=self.build_temp
  File "/opt/python/2.7.15.1/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'ON', '--target', 'sonata_python', '--', '-j']' returned non-zero exit status 2
==> Error: ProcessError: Command exited with status 1:
    '/opt/python/2.7.15.1/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'

8 errors found in build log:
     72    0x6268d2 lto_main()
     73    	../../cray-gcc-6.2.0/gcc/lto/lto.c:3304
     74    Please submit a full bug report,
     75    with preprocessed source if appropriate.
```

GCC 7.3.0 build works fine.

**Comment by mgeplf** [comment]
Suspicious LTO issues w/ pybind11.  Do the other pybind11 projects have the same problem?

Do you get an error w/ doing `spack install py-pybind11`

**Comment by mgeplf** [comment]
@pramodk is this still relevant? If it is, what are the anwers to the above questions?

**Comment by mgeplf** [comment]
I'm going to close this; please reopen it if you continue to have errors.

**Comment by pramodk** [comment]
Sorry, missed this.

I think we are not seeing any errors now. @jorblancoa : can you confirm?

**Comment by jorblancoa** [comment]
py-libsonata is installed in daint with gcc 8.3.0 without any problems!
